zilliztech/phantoscope

- docs/site/en/examples/object.md
- docs/site/en/quickstart/README.md
documentation
fix command errror in en doc
> fix command error

- docs/site/en/examples/object.md
- docs/site/en/quickstart/README.md
- docs/site/zh-CN/quickstart/README.md
documentation
fix en object doc
> Quick start docs3

- docs/site/zh-CN/examples/object.md
documentation
add change application information
> add app change information

- operators/face-detector/face_detector.py
- operators/face-encoder/face_embedding.py
- operators/mask-rcnn-detector/mask_rcnn.py
- operators/mask-rcnn-detector/mrcnn/model.py
- operators/ssd-detector/ssd.py
- operators/ssd-encoder/ssd.py
- operators/yolov3-detector/paddle_yolo.py
> enhance code quality

- search/operators/runtime.py
api-change / bug / design / documentation / feature
Fixes #
> fix,return port information when instance created

- search/pipeline/pipeline.py
- tests/test_pipeline.py
- tests/utils/require.py
> update pipeline tests

- search/application/application.py
- search/application/application_api.py
- search/application/score/field_decay.py
- search/application/search.py
- search/application/upload.py
- search/common/error.py
- search/storage/storage.py
bug 
fix bugs about multi pipeline score function
> fix score function error and  format code

- scripts/load_data.py
> fix typo in  load_data.py

- search/application/application.py
- search/application/application_api.py
- search/storage/storage.py
- tests/test_application.py
api-change & feature
add entity count #124 #30
Fixes #124 #30
> add entity count and pagination api

- tests/test_application.py
- tests/test_score_function.py
> format test code

- docs/site/zh-CN/tutorials/operator.md
documentation 
fix 0.1.0 doc link error
Fixes #128
> fix 0.1.0 doc link error

- search/storage/storage.py
> fix args not define bug

- docker-compose.yml
- scripts/load_data.py
documentation
fix load data error in macos which upload url is undefined 
Fixes #130
> fix 0.1.0 load data script about undefined upload_url

- README.md
- README_CN.md
documentation
change command to select default branch when clone
> add branch select in readme

- docs/site/en/tutorials/operator.md
- docs/site/zh-CN/tutorials/operator.md
api-change / bug / design / documentation / feature
Fixes #
> [skip ci] Updated the EN translation of operator.md.

- .github/workflows/operator.yml
- docker-compose.yml
- docs/site/en/quickstart/README.md
- docs/site/en/tutorials/preview.md
- docs/site/zh-CN/quickstart/README.md
- docs/site/zh-CN/tutorials/preview.md
documentation
prepare to tag v0.2.0
> fix version of api-server and preview in docs and docker-compose

- docs/site/en/examples/object.md
documentation
fix en object doc about application name
> fix en object doc about application name

- README.md
- README_CN.md
- docs/site/en/quickstart/README.md
- docs/site/en/tutorials/preview.md
- docs/site/zh-CN/examples/object.md
- docs/site/zh-CN/quickstart/README.md
- docs/site/zh-CN/tutorials/preview.md
documentation 
change api doc link and delete gif file
> Change api doc link and delete gif file

- docs/site/en/tutorials/application.md
- docs/site/zh-CN/tutorials/application.md
documentation 
add score function doc entry in application introduction page
> add score function doc entry in application introduction page

- operators/face-detector/Dockerfile
- operators/face-detector/Dockerfile-gpu
- operators/face-detector/server.py
- operators/face-encoder/server.py
- search/pipeline/pipeline.py
- search/resource/resource.py
bug
Fix port bug in face-encoder and face-detector opertaor
Fixes #157
> fix operator port bug
